version: 2
updates:
  # Monitor npm packages in the client directory
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # Monitor npm packages in the server directory
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
